config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :saved_entries, only: [:create, :destroy]

  resources :wallets do
    member do
      get 'connect_to_wallet'
    end
    resources :transactions, only: [:index, :create]
    resources :currency_amounts, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
class Currency < ApplicationRecord
  has_many :currency_amounts
end

app/models/currency_amount.rb
class CurrencyAmount < ApplicationRecord
  belongs_to :wallet
  belongs_to :currency
end

app/models/saved_entry.rb
class SavedEntry < ApplicationRecord
  belongs_to :wallet
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :currency_amounts
  has_many :saved_entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

end

app/controllers/currency_amounts_controller.rb
# app/controllers/currency_amounts_controller.rb

class CurrencyAmountsController < ApplicationController
  before_action :set_wallet

  def create
    @currency_amount = @wallet.currency_amounts.build(currency_amount_params)

    respond_to do |format|
      if @currency_amount.save
        format.html { redirect_to @wallet }
        format.js
      else
        format.html { render 'wallets/show' }
        format.js { render partial: 'shared/errors', locals: { object: @currency_amount } }
      end
    end
  end

  def destroy
    @currency_amount = @wallet.currency_amounts.find(params[:id])
    @currency_amount.destroy

    respond_to do |format|
      format.html { redirect_to @wallet }
      format.js
    end
  end

  private

  def set_wallet
    @wallet = Wallet.find(params[:wallet_id])
  end

  def currency_amount_params
    params.require(:currency_amount).permit(:currency, :amount)
  end
end

app/controllers/saved_entries_controller.rb
class SavedEntriesController < ApplicationController
  def create
    @wallet = Wallet.find(params[:wallet_id])
    @saved_entry = @wallet.saved_entries.build(saved_entry_params)

    if @saved_entry.save
      redirect_to @wallet
    else
      render 'wallets/show'
    end
  end

  def destroy
    @saved_entry = SavedEntry.find(params[:id])
    @wallet = @saved_entry.wallet

    if @saved_entry.destroy
      redirect_to @wallet
    else
      render 'wallets/show'
    end
  end

  private

  def saved_entry_params
    params.require(:saved_entry).permit(:wallet_address, :amount)
  end
end

app/controllers/wallets_controller.rb
require 'eth'

class WalletsController < ApplicationController

  before_action :set_wallet, only: [:show, :edit, :update, :destroy]

  def connect_to_wallet
    provider = Eth::Http::Client.new('https://mainnet.infura.io/v3/your_infura_project_id')

    # Add the necessary logic to connect the user's wallet
    if provider.connected?
      # The wallet is already connected
      flash[:notice] = "Wallet already connected"
      redirect_to @wallet
    else
      # Prompt the user to connect their MetaMask wallet
      begin
        provider.enable
        flash[:notice] = "Wallet connected successfully"
        redirect_to @wallet
      rescue Eth::ProviderError => e
        flash[:error] = "Failed to connect wallet: #{e.message}"
        redirect_to root_path
      end
    end
  end

  def show
    @currency_amount = @wallet.currency_amounts.build
    @saved_entries = SavedEntry.all
  end

  def create
    @wallet = Wallet.new(wallet_params)

    if @wallet.save
      redirect_to @wallet
    else
      render :new
    end
  end

  def destroy
    @wallet.destroy
    redirect_to wallets_url
  end

  def save_entry
    @saved_entry = SavedEntry.new(saved_entry_params)

    if @saved_entry.save
      broadcast_saved_entry(@saved_entry)
      head :ok
    else
      render json: @saved_entry.errors, status: :unprocessable_entity
    end
  end

  def delete_entry
    SavedEntry.find(params[:id]).destroy
    head :ok
  end

  def index
    @currencies = Currency.all
  end

  def add_currency
    currency = Currency.create(currency_params)

    if currency.persisted?
      render json: { id: currency.id, address: currency.address, amount: currency.amount }
    else
      render json: { error: currency.errors.full_messages.join(', ') }, status: :unprocessable_entity
    end
  end

  def delete_currency
    Currency.find(params[:id]).destroy
    render json: { success: true }
  end

  private

  def set_wallet
    @wallet = Wallet.find(params[:id])
  end

  def wallet_params
    params.require(:wallet).permit(:name, :description)
  end

  def saved_entry_params
    params.require(:saved_entry).permit(:wallet_address, :amount)
  end

  def broadcast_saved_entry(saved_entry)
    ActionCable.server.broadcast('wallet_channel', saved_entry: render_saved_entry(saved_entry))
  end

  def render_saved_entry(saved_entry)
    ApplicationController.renderer.render(partial: 'saved_entries/saved_entry', locals: { saved_entry: saved_entry })
  end

  def currency_params
    params.permit(:address, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wallet_helper.rb
module WalletHelper
end

app/views/currency_amounts/ destroy.js.erb
// app/views/currency_amounts/destroy.js.erb

$('#currency-amount-<%= @currency_amount_id %>').remove();

app/views/currency_amounts/_form.html.erb
<%= form_with(model: wallet, local: true) do |form| %>
  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currency_amounts/create.js.erb
// app/views/currency_amounts/create.js.erb

$('#currency-amounts').append('<%= j render partial: "currency_amount", locals: { currency_amount: @currency_amount } %>');

$('#currency_amount_currency').val('');
$('#currency_amount_amount').val('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Polykick</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wallets/connect_to_wallet.html.erb
<h1>Connect to Wallet</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% elsif flash[:error] %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

<p>Click the button below to connect your MetaMask wallet:</p>

<%= link_to "Connect Wallet", connect_to_wallet_wallet_path(@wallet), class: "button" %>

app/views/wallets/edit.html.erb
<h1>Edit Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show',

app/views/wallets/index.html.erb
<!-- app/views/wallets/index.html.erb -->

<table id="currency-table">
  <thead>
    <tr>
      <th>Address</th>
      <th>Currency Amount</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @currencies.each do |currency| %>
      <tr data-id="<%= currency.id %>">
        <td class="wallet-address"><%= currency.address %></td>
        <td class="amount"><%= currency.amount %></td>
        <td>
          <button class="btn btn-danger delete-btn">Delete</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<form id="add-currency-form">
  <div class="form-group">
    <label for="address">Address:</label>
    <input type="text" class="form-control" id="address" name="address">
  </div>
  <div class="form-group">
    <label for="amount">Amount:</label>
    <input type="text" class="form-control" id="amount" name="amount">
  </div>
  <button type="submit" class="btn btn-primary">Add Entry</button>
</form>

<script src="<%= asset_path 'wallets/index.js' %>"></script>

app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<h2>Currency Amounts:</h2>
<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @wallet.currency_amounts.each do |currency_amount| %>
      <tr>
        <td><%= currency_amount.currency.address %></td>
        <td><%= currency_amount.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>